### ISSUE TITLE
Fill in README for canopy cover transformer

### ISSUE THREAD

**Issue by jvanderleeuw** [terraref/tutorials#243] opened 2020-04-21 17:31 UTC
The README for the instructions for building, testing, and deploying the canopy cover transformer should be filled in

**Comment by KristinaRiemer** [comment] 2020-04-22 18:15
Is this issue in the right place? This repo is for the [TERRA REF tutorials website](https://terraref.github.io/tutorials/), is the README going on this website or somewhere in [the pipeline organization](https://github.com/agPipeline)?

**Comment by dlebauer** [comment] 2020-05-08 16:46
This is really a duplicate of or should be an issue within https://github.com/AgPipeline/issues-and-projects/issues/90

**Closed by dlebauer** 2020-05-08 16:46 UTC
